// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using RateOple.Infrastructure.Data;

#nullable disable

namespace RateOple.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class AddAccountLifecycleHardening
    {
    }
}
